# This is a basic workflow to help you get started with Actions

name: 新部署

on:
  push:
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: 下载ssh秘钥
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVKEY }}
          name: 'deploy_key'
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts 

      - name: 检查秘钥和hosts
        run: |
          cd ~/.ssh
          ls -ao
          cat ./known_hosts
          cat ./id_rsa

      - name: 设置 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: 安装Node.js
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      # 安装依赖
      - name: 安装依赖
        run: pnpm install
      # 构建
      - name: 构建
        run: pnpm run docs:build
        
      # SFTP部署到服务器
      # - name: 推送
      #   uses: wlixcc/SFTP-Deploy-Action@v1.0
      #   with:  
      #     username: '${{ secrets.USER }}'   #ssh user name
      #     server: '${{ secrets.IP }}' #引用之前创建好的secret
      #     ssh_private_key: ${{ secrets.PRIVKEY }} #引用之前创建好的secret
      #     local_path: './docs/.vuepress/dist/*'  # 对应我们项目build的文件夹路径
      #     remote_path: '/web/blog'

      # Rsync部署到服务器
      - name: 推送
        uses: contention/rsync-deployments@v2.0.0
        with:
          flags: -avz --delete
          excludes: 
          deploy_key: '~/.ssh/deploy_key'
          user: ${{ secrets.USER }}
          host: ${{ secrets.IP }}
          localpath: 'docs/.vuepress/dist'
          remotepath: '/web/blog'